// <auto-generated />
using System;
using ExpanseTracker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ExpanseTracker.Migrations
{
    [DbContext(typeof(ExpanseTrackerContext))]
    partial class ExpanseTrackerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ExpanseTracker.Data.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Travel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Entertainment"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Clothes"
                        },
                        new
                        {
                            Id = 6,
                            Name = "House"
                        });
                });

            modelBuilder.Entity("ExpanseTracker.Data.Models.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Planned")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Expenses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 23000.0,
                            CategoryId = 2,
                            Date = new DateTime(2022, 7, 17, 21, 0, 0, 0, DateTimeKind.Utc),
                            Planned = true,
                            Title = "Hawaii"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3.5,
                            CategoryId = 1,
                            Date = new DateTime(2023, 7, 17, 21, 0, 0, 0, DateTimeKind.Utc),
                            Planned = false,
                            Title = "Bubble Gum"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20.0,
                            CategoryId = 5,
                            Date = new DateTime(2012, 7, 17, 21, 0, 0, 0, DateTimeKind.Utc),
                            Planned = true,
                            Title = "Sun glasses"
                        },
                        new
                        {
                            Id = 4,
                            Amount = 25.0,
                            CategoryId = 4,
                            Date = new DateTime(2031, 7, 17, 21, 0, 0, 0, DateTimeKind.Utc),
                            Planned = false,
                            Title = "Calculator"
                        });
                });

            modelBuilder.Entity("ExpanseTracker.Data.Models.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Income");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2500.0,
                            Date = new DateTime(2022, 1, 31, 22, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Ropardo_January",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Amount = 0.40000000000000002,
                            Date = new DateTime(2022, 9, 20, 21, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Cash on the street",
                            Type = 3
                        },
                        new
                        {
                            Id = 3,
                            Amount = 500.0,
                            Date = new DateTime(2012, 9, 14, 21, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Erasmus",
                            Type = 1
                        });
                });

            modelBuilder.Entity("ExpanseTracker.Data.Models.Expense", b =>
                {
                    b.HasOne("ExpanseTracker.Data.Models.Category", "Category")
                        .WithMany("Expenses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ExpanseTracker.Data.Models.Category", b =>
                {
                    b.Navigation("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
